name = "RelearnNyiyui"
license = "MIT"
licenselink = "https://github.com/colourdelete/RelearnNyiyui/blob/main/LICENSE"
description = "A theme for Hugo designed for documentation"
homepage = "https://github.com/colourdelete/RelearnNyiyui"
tags = ["docs", "documentation", "grav", "learn", "multilingual", "relearn", "search"]
features = ["documentation", "expand", "include", "menu", "mermaid", "multilingual", "nested sections", "notice", "search", "tabs", "themeable"]

[author]
  name = "Ken Shibata"
  homepage = "https://github.com/colourdelete"

[original]
  author = "Sören Weber"
  homepage = "https://github.com/McShelby"
